"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[52],{65273:function(l,e,n){n.d(e,{Z:function(){return g}});var d=n(62435),o=n(65275),t=n(36029),c=n(29671),a=n(20640),r=n.n(a),h=n(33862),u=n(1210),v=n(85093),m=n(10524),x=n(14079),s=n(49721),j=n.p+"static/logo.4700deb7.png",f="Mphil student in CIE",i=n(86074),g=function(){var N=function(S){S.preventDefault(),r()(s.email),o.ZP.success("Email copied to clipboard",1)};return(0,i.jsxs)("div",{className:"sidebar",children:[(0,i.jsxs)("div",{className:"profile",children:[(0,i.jsx)(t.C,{size:{xs:48,sm:64,md:80,lg:128,xl:160,xxl:200},src:j}),(0,i.jsxs)("div",{className:"info",children:[(0,i.jsx)("div",{className:"name",children:s.name}),(0,i.jsx)("div",{className:"shortInfo",children:(0,i.jsx)(c.U,{children:f})})]})]}),(0,i.jsxs)("div",{className:"link",children:[(0,i.jsxs)("div",{children:[(0,i.jsx)(h.Z,{className:"icon"}),s.location]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(u.Z,{className:"icon"}),(0,i.jsx)("a",{href:s.github,children:"Github"})]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(v.Z,{className:"icon"}),(0,i.jsx)("a",{href:s==null?void 0:s.twitter,children:"Twitter"})]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(m.Z,{className:"icon"}),(0,i.jsx)("a",{onClick:N,href:"",children:"Email"})]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(x.Z,{className:"icon"}),(0,i.jsx)("a",{href:s==null?void 0:s.googleScholar,children:"Google Scholar"})]})]})]})}},76070:function(l,e,n){n.r(e),n.d(e,{default:function(){return r}});var d=n(62435),o=`# Selected/Recent Publications\r
\r
## SPES: Towards Optimizing Performance-Resource Trade-Off for Serverless Functions\r
Cheryl Lee, Tianyi Yang, **Zhouruixing Zhu**, Yuxin Su, Pinjia He, Michael R Lyu\r
\r
## Hue: A user-adaptive parser for hybrid logs\r
Junjielong Xu, Qiuai Fu, **Zhouruixing Zhu**, Yutong Cheng, Zhijing Li, Yuchi Ma, Pinjia He\r
*ESEC/FSE'23: Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering*\r
\r
`,t=n(65273),c=n(29671),a=n(86074),r=function(){return(0,a.jsxs)("div",{className:"page",children:[(0,a.jsx)(t.Z,{}),(0,a.jsxs)("div",{className:"content",children:[(0,a.jsx)("div",{className:"title",children:"Selected/Recent Publications"}),(0,a.jsx)("div",{className:"markdown",children:(0,a.jsx)(c.U,{children:o})})]})]})}},49721:function(l){l.exports=JSON.parse('{"name":"Zhouruixing Zhu","location":"ShenZhen, China","email":"zhouruixingzhu@link.cuhk.edu.cn","github":"https://github.com/shuaijiumei","googleScholar":"https://scholar.google.com.hk/citations?user=bKNg57IAAAAJ&hl=zh-CN","showBar":["aboutme","publications","services","cv"]}')}}]);
