"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[767],{65273:function(o,a,n){n.d(a,{Z:function(){return g}});var d=n(62435),l=n(65275),t=n(36029),r=n(29671),e=n(20640),c=n.n(e),h=n(33862),v=n(1210),m=n(85093),u=n(10524),x=n(14079),i=n(49721),f=n.p+"static/logo.4700deb7.png",j=`Mphil student in [CIE](https://sse-mphil-phd.cuhk.edu.cn/program/CIE)\r
`,s=n(86074),g=function(){var E=function(S){S.preventDefault(),c()(i.email),l.ZP.success("Email copied to clipboard",1)};return(0,s.jsxs)("div",{className:"sidebar",children:[(0,s.jsxs)("div",{className:"profile",children:[(0,s.jsx)(t.C,{size:{xs:48,sm:64,md:80,lg:128,xl:160,xxl:200},src:f}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("div",{className:"name",children:i.name}),(0,s.jsx)("div",{className:"shortInfo",children:(0,s.jsx)(r.U,{children:j})})]})]}),(0,s.jsxs)("div",{className:"link",children:[(0,s.jsxs)("div",{children:[(0,s.jsx)(h.Z,{className:"icon"}),i.location]}),(0,s.jsxs)("div",{children:[(0,s.jsx)(v.Z,{className:"icon"}),(0,s.jsx)("a",{href:i.github,children:"Github"})]}),(0,s.jsxs)("div",{children:[(0,s.jsx)(m.Z,{className:"icon"}),(0,s.jsx)("a",{href:i==null?void 0:i.twitter,children:"Twitter"})]}),(0,s.jsxs)("div",{children:[(0,s.jsx)(u.Z,{className:"icon"}),(0,s.jsx)("a",{onClick:E,href:"",children:"Email"})]}),(0,s.jsxs)("div",{children:[(0,s.jsx)(x.Z,{className:"icon"}),(0,s.jsx)("a",{href:i==null?void 0:i.googleScholar,children:"Google Scholar"})]})]})]})}},92244:function(o,a,n){n.r(a),n.d(a,{default:function(){return c}});var d=n(62435),l=`### 2024\r
- External Reviewer \u2013 46th International Conference on Software Engineering (ICSE 2024)\r
- External Reviewer \u2013 33rd ACM International Conference on the Foundations of Software Engineering (FSE 2024)\r
\r
### 2023\r
- External Reviewer \u2013 32nd ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE 2023)\r
- External Reviewer \u2013 34th IEEE International Symposium on Software Reliability Engineering (ISSRE 2023)\r
`,t=n(65273),r=n(29671),e=n(86074),c=function(){return(0,e.jsxs)("div",{className:"page",children:[(0,e.jsx)(t.Z,{}),(0,e.jsxs)("div",{className:"content",children:[(0,e.jsx)("div",{className:"title",children:"Services"}),(0,e.jsx)("div",{className:"markdown",children:(0,e.jsx)(r.U,{children:l})})]})]})}},49721:function(o){o.exports=JSON.parse('{"name":"Zhouruixing Zhu","location":"ShenZhen, China","email":"zhouruixingzhu@link.cuhk.edu.cn","github":"https://github.com/Zhuzrx","googleScholar":"https://scholar.google.com.hk/citations?user=bKNg57IAAAAJ&hl=zh-CN","showBar":["About","Publications","Services","CV"]}')}}]);
