"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[767],{65273:function(o,a,n){n.d(a,{Z:function(){return g}});var d=n(62435),l=n(46837),r=n(8250),t=n(29671),e=n(20640),c=n.n(e),h=n(33862),v=n(1210),m=n(85093),u=n(10524),x=n(14079),s=n(49721),f=n.p+"static/logo.4700deb7.png",j="Mphil student in CUHKSZ.  ",i=n(86074),g=function(){var S=function(E){E.preventDefault(),c()(s.email),l.ZP.success("Email copied to clipboard",1)};return(0,i.jsxs)("div",{className:"sidebar",children:[(0,i.jsxs)("div",{className:"profile",children:[(0,i.jsx)(r.C,{size:{xs:48,sm:64,md:80,lg:128,xl:160,xxl:200},src:f}),(0,i.jsxs)("div",{className:"info",children:[(0,i.jsx)("div",{className:"name",children:s.name}),(0,i.jsx)("div",{className:"shortInfo",children:(0,i.jsx)(t.U,{children:j})})]})]}),(0,i.jsxs)("div",{className:"link",children:[(0,i.jsxs)("div",{children:[(0,i.jsx)(h.Z,{className:"icon"}),s.location]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(v.Z,{className:"icon"}),(0,i.jsx)("a",{href:s.github,children:"Github"})]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(m.Z,{className:"icon"}),(0,i.jsx)("a",{href:s==null?void 0:s.twitter,children:"Twitter"})]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(u.Z,{className:"icon"}),(0,i.jsx)("a",{onClick:S,href:"",children:"Email"})]}),(0,i.jsxs)("div",{children:[(0,i.jsx)(x.Z,{className:"icon"}),(0,i.jsx)("a",{href:s==null?void 0:s.googleScholar,children:"Google Scholar"})]})]})]})}},92244:function(o,a,n){n.r(a),n.d(a,{default:function(){return c}});var d=n(62435),l=`# Service\r
\r
## 2024\r
\r
- External Reviewer \u2013 46th International Conference on Software Engineering (ICSE 2024)\r
- External Reviewer \u2013 33rd ACM International Conference on the Foundations of Software Engineering (FSE 2024)\r
\r
### 2023\r
- External Reviewer \u2013 32nd ACM Joint European Software Engineering Conference and Symposium on the Foundations of Software Engineering (ESEC/FSE 2023)\r
- External Reviewer \u2013 34th IEEE International Symposium on Software Reliability Engineering (ISSRE 2023)\r
`,r=n(65273),t=n(29671),e=n(86074),c=function(){return(0,e.jsxs)("div",{className:"page",children:[(0,e.jsx)(r.Z,{}),(0,e.jsxs)("div",{className:"content",children:[(0,e.jsx)("div",{className:"title",children:"Services"}),(0,e.jsx)("div",{className:"markdown",children:(0,e.jsx)(t.U,{children:l})})]})]})}},49721:function(o){o.exports=JSON.parse('{"name":"Zhouruixing Zhu","location":"ShenZhen, China","email":"zhouruixingzhu@link.cuhk.edu.cn","github":"https://github.com/shuaijiumei","googleScholar":"https://scholar.google.com.hk/citations?user=bKNg57IAAAAJ&hl=zh-CN","showBar":["aboutme","publications","services","cv"]}')}}]);
